// SPDX-License-Identifier: GPL-3.0-only

// Code generated by protoc-gen-sol. DO NOT EDIT.
// source: contracts/libraries/proto/farming.proto
pragma solidity 0.8.9;
import "./Pb.sol";

library PbFarming {
    using Pb for Pb.Buffer; // so we can call Pb funcs on Buffer obj

    struct FarmingRewards {
        address recipient; // tag: 1
        uint256 chainId; // tag: 2
        address[] tokenAddresses; // tag: 3
        uint256[] cumulativeRewardAmounts; // tag: 4
    } // end struct FarmingRewards

    function decFarmingRewards(bytes memory raw) internal pure returns (FarmingRewards memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint256[] memory cnts = buf.cntTags(4);
        m.tokenAddresses = new address[](cnts[3]);
        cnts[3] = 0; // reset counter for later use
        m.cumulativeRewardAmounts = new uint256[](cnts[4]);
        cnts[4] = 0; // reset counter for later use

        uint256 tag;
        Pb.WireType wire;
        while (buf.hasMore()) {
            (tag, wire) = buf.decKey();
            if (false) {}
            // solidity has no switch/case
            else if (tag == 1) {
                m.recipient = Pb._address(buf.decBytes());
            } else if (tag == 2) {
                m.chainId = Pb._uint256(buf.decBytes());
            } else if (tag == 3) {
                m.tokenAddresses[cnts[3]] = Pb._address(buf.decBytes());
                cnts[3]++;
            } else if (tag == 4) {
                m.cumulativeRewardAmounts[cnts[4]] = Pb._uint256(buf.decBytes());
                cnts[4]++;
            } else {
                buf.skipValue(wire);
            } // skip value of unknown tag
        }
    } // end decoder FarmingRewards
}
