// Code generated by protoc-gen-sol. DO NOT EDIT.
// source: signer.proto
pragma solidity >=0.5.0;
import "./Pb.sol";

library PbSigner {
    using Pb for Pb.Buffer;  // so we can call Pb funcs on Buffer obj

    struct Signer {
        address address;   // tag: 1
        uint256 tokens;   // tag: 2
    } // end struct Signer

    function decSigner(bytes memory raw) internal pure returns (Signer memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint tag;
        Pb.WireType wire;
        while (buf.hasMore()) {
            (tag, wire) = buf.decKey();
            if (false) {} // solidity has no switch/case
            else if (tag == 1) {
                m.address = Pb._address(buf.decBytes());
            }
            else if (tag == 2) {
                m.tokens = Pb._uint256(buf.decBytes());
            }
            else { buf.skipValue(wire); } // skip value of unknown tag
        }
    } // end decoder Signer

    struct SortedSigners {
        Signer[] signers;   // tag: 1
    } // end struct SortedSigners

    function decSortedSigners(bytes memory raw) internal pure returns (SortedSigners memory m) {
        Pb.Buffer memory buf = Pb.fromBytes(raw);

        uint[] memory cnts = buf.cntTags(1);
        m.signers = new Signer[](cnts[1]);
        cnts[1] = 0;  // reset counter for later use
        
        uint tag;
        Pb.WireType wire;
        while (buf.hasMore()) {
            (tag, wire) = buf.decKey();
            if (false) {} // solidity has no switch/case
            else if (tag == 1) {
                m.signers[cnts[1]] = decSigner(buf.decBytes());
                cnts[1]++;
            }
            else { buf.skipValue(wire); } // skip value of unknown tag
        }
    } // end decoder SortedSigners

}
